### DISCUSSION TITLE
Warmwasser zubereiten starten

### DISCUSSION THREAD

**Discussion by propi62** [open3e/open3e#243] [Q&A]
Guten Tag
Ich habe eine kleine Solaranlage 800W peak. Jetzt möchte ich die Warmwasserzubereitung über die Ausseneinheit selber starten können, sobald die Solaranlage überflüssigen Strom produziert. Dies könnte ich über Homeassistant regeln.

Meine Vitocal ist auf 48 Grad Warmwasser eingestellt mit einer Hysterese von 5 Grad.
Die Heizung startet, sobald das Wasser unter 43 Grad fällt.
Nun möchte ich aber schon bei zB 45 Grad das Aufheizen starten.

Es gibt ja die "Einmalige Warmwasserbereitung" welche ich schon über Homeassistant starten könnte. Jedoch funktioniert diese Funktion nicht so, wie ich möchte.

Wäre es möglich über open3e MQTT einen command abzusetzen um das Aufheizen sofort zu starten.

Ich habe glaub mal eine Methode gesehen, in der temporär die Hysterese verstellt wird. Diese Methode möchte ich aber umgehen.

Gruss

**Comment by Dreman65** [comment]
Ist (wahrscheinlich) identisch zur Heizkreispumpe: einen speziellen Parameter zum direkten Schalten des WW außerhalb der Geräte-Regelung hab ich bisher nicht gefunden. Funktioniert also nur indirekt, indem man die entsprechenden WW-Parameter der Regelung anpasst (z.B. die Hysterese), aber das willst du ja umgehen. Warum eigentlich?

**Comment by coreYalfons** [comment]
Probiers mal mit denen, damit kannst du per write die beiden ansprechen "on/off"
open3/Vitocal-200s_680_1006_TargetQuickMode/Required
open3/Vitocal-200s_680_1007_CurrentQuickMode/Required

**Comment by coreYalfons** [comment]
Also ich habs bei mir getestet und implementiert, hier ist der Switch dazu. Es muss zu Required scheinbar auch der OpMode auf 2 gesetzt werden. 1007 ist glaube ich nicht beschreibar, nur 1006. 

```
mqtt:
  switch:
    - name: "Vitocal Einmaliges Warmwasser"
      unique_id: 1006_TargetQuickModeRequired
      default_entity_id: swtich.680_1006_TargetQuickModeRequired
      state_topic: "open3e_vitocal/680_1006_TargetQuickMode/Required"
      device:
        name: "Vitocal200-S"
        identifiers: !secret vitocal_sn
        manufacturer: "Viessmann"
        model: "Vitocal 200-S"
      payload_on: "on"
      payload_off: "off"
      state_on: "on"
      state_off: "off"
      optimistic: false
      qos: 0
      retain: true
      command_topic: "open3e/cmnd"
      command_template: >
        {% set values = { 'on':'02010000', 'off':'00000000'} %}
        {% set cmd = {'mode': 'write-raw', 'data':[[1006, values[value]]]} %}
        {{ cmd | to_json }}
```
