### DISCUSSION TITLE
Hardware question Pi 3 B+, POE with 3 Relay HAT, CAN-HAT

### DISCUSSION THREAD

**Discussion by Parateam** [open3e/open3e#86] [Q&A]
Hello, i want to get independent from Viessmann with my 252-A heatpump. I use Homeassistant with many ESP32. Now i have an ESP32 board with power supply and 4 relays. I switch the smart grid states an the domestic circulation pump.

Now, i want to use open3e with CAN, Ethernet connection with POE and 3 relays for SG and circulation pump. Is this possible? The CAN interface works with wiringPi library and can0 is with ifconfig visible. The CAN chip works with SPI interface. 

There is also an Intergration in Homeassistant to define switches for the relays with the integration "remote_rpi_gpio". This should work parallel with open3e.

I think this is a nice solution. All HATS can stacked and POE with ethernet is also there.

Here are the details of the hardware:
--PI3 B+
--POE 3 relay and POE HAT 
       https://www.amazon.de/-/en/RPi-Relay-Board-Module-Raspberry/dp/B08PZGXMTK
--[Pi Zero Shield - RS485 CAN HAT, MCP2515]
       https://www.waveshare.com/wiki/RS485_CAN_HAT

Thanks for your reply,
Peter

**Comment by Wolfgang-03** [comment]
Hi Peter, 

I can't tell you much about your hardware question, but I have a similar setup to yours. Home Assisant, solar system with battery storage, Viessmann heat pump, wallboxes. 

I'm currently working on a solution for the most efficient way to control my Viessmann heat pump in conjunction with my solar system. I have already experimented with the Viessmann SG Ready function. However, the SG doesn't seem to do anything other than raise the flow temperature. This can also be achieved directly via Open3E (Canbus) by simply setting the temperature for the heating circuit upwards. You don't need any extra hardware to control the SG inputs. I can also control the PV consumption much more precisely this way, with SG there is only on/off and this can lead to unwanted charging cycles in the home storage system. 

My procedure is as follows. In the morning, shortly before or after the family leaves the house, I lower the room temperature (e.g. to 15 degrees), so that the heat pump switches off and no longer requires electricity. As soon as the battery home storage is charged to more than 20% and electricity (> 1000 W) is coming from the roof, I gradually switch the temperature up again (e.g. check every 5 minutes if (PV electricity) - (home consumption) > 1000 watts -> + 1 degree). If there is a PV surplus, it can also be higher than the standard room temperature of 22 degrees. 

All of this only works with Home Assistant and Open3E (CanBus USB adapter for Open3E) without any other hardware.

The circulation pump is an issue that is still open for me, but in principle it should also be possible to control it directly via Open3E. Perhaps even more precisely with speed control. I haven't looked at this yet.

best regards
Wolfgang

**Reply by jwende** [reply]
Just wondering which circulation pump you have in mind? Domestic hot water? You want to use the digital signal to request a x minute activation?
If this is the case - you don't need any additional hardware - you could simply add a new schedule into the DHW scheduler - e.g. from now to now+15 minutes and leave the other DHW circulation settings as is. This could be done either with open3e or with the existing viessmann cloud API.
And SG Ready ... I would agree with Wolfgang. The simple on/off switch doesn't make any sense - especially if you have any sort of home automation in place that could react on PV production/ battery charge level or even current energy prices.
Cheers
Joerg

**Reply by Wolfgang-03** [reply]
In case anyone is searching for it. I have now develpoed a controller with which you can change the speed/performance of the heating circuit pumps via Open3e/MQTT. The principle should be applicable to any controllable pump.

[Open3E-HA](https://github.com/Wolfgang-03/Open3E-HA)
[Open3E-HA -Vitocal250.yaml](https://github.com/Wolfgang-03/Open3E-HA/blob/main/config/packages/vitocal250.yaml)

**Reply by jwende** [reply]
Just changed the target values - but where can I see the current value?

**Reply by Philip-Wiege** [reply]
The current actual relative speed of the circulation pump (pump for heating and domestic hot water) is in the DID 2791 CentralHeatingPumpStatus

I'm using it in my HA visualization as you can see here (actual vs setpoint)

![image](https://github.com/open3e/open3e/assets/19406918/e15e5a81-3b61-49fe-aa35-666ef9848fd4)

**Reply by jwende** [reply]
I get the following value from the system:

python3 Open3Eclient.py -c can0 -dev vcal -r 2791 -v
vcal 2791 CentralHeatingPumpStatus 100.0
closing 0x680 - bye!

But the the settings are:

python3 Open3Eclient.py -c can0 -dev vcal -r 1103
{'MinSpeed': 20.0, 'MaxSpeed': 100.0, 'Setpoint': 80.0}

**Reply by Philip-Wiege** [reply]
Strange. I am using CentralHeatingPump for the setpoint and CentralHeatingPumpStatus for the actual value. The values match the shown values on the IDU.

The setpoint from the "min, max, setpoint" array DIDs did not match the setpoint in the service menu on my IDU.

I have a recently installed Vitocal 250-A with no heating buffers so there is only the internal pump.

**Reply by Wolfgang-03** [reply]
Perhaps I rejoiced too soon? But even if I set MaxSpeed to Setpoint on the HK1 (1102)

`{% set cmddata = '14' + '%0x' % intvalue + '%0x' % intvalue %}`

2792 is still on 100%!? I have not yet observed the 2792 at all. I'll have the value recorded now and see if anything changes at all. 

I would have expected to see the same behaviour at 1100 / 2791, but when I try to set the value of 1100, 

```
    - name: "Primärpumpe Wärmeerzeuger"
      unique_id: open3e_CentralHeatingPump_Control
      object_id: open3e_centralheatingpumpcontrol
      device:
        name: "Open3e_Vitocal250A"
        identifiers: "S/N xxxxx"
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
        suggested_area: "Heizung"
      device_class: power_factor
      min: 20
      max: 100
      step: 5
      unit_of_measurement: "%"
      state_topic: "open3e/680_1100_CentralHeatingPumpMinimumMaximumLimit/Setpoint"
      command_topic: "open3e/cmnd"
      # MinSpeed = $14 = #20
      # MaxSpeed = $64 = #100
      # Setpoint = value
      command_template: >
        {% set intvalue = value | int %}
        {% set cmddata = '1464' + '%0x' % intvalue %}
        {% set cmd = {'mode': 'write-raw', 'data': [[1100, cmddata]]} %}
        {{ cmd | to_json }}
      icon: mdi:pump

```
open3e raises the following error. 
        
![image](https://github.com/open3e/open3e/assets/80253488/9b655c88-1e86-4b65-9b62-0768d7336cc8)

any ideas why?
