### ISSUE TITLE
Vitocal 250-a can communication with ESPHome

### ISSUE THREAD

**Issue by Scarbous** [open3e/open3e#166]
Hi,
this is not directly a question about the project, but it is about communicate with my Viessmann Vitocal 250-a over can.

I would like to use ESPHome with a CAN module to read the data from my Vitocal 250-a.

I have already created a config with which I can send all messages via MQTT, but only the following IDs arrive 0,1793,511,400,2021

Now I am unsure whether something additional needs to be activated or whether I need to actively query data via can.

I have not found anything about this in the installation instructions for open3e.

-----

Here is my current canbus ESPHome YAML.
It uses the canID as part of the topic.

```yaml
spi:
  id: McpSpi
  clk_pin: GPIO16
  mosi_pin: GPIO05
  miso_pin: GPIO04

canbus:
  - platform: mcp2515
    spi_id: McpSpi
    cs_pin: GPIO14
    can_id: 0x0
    bit_rate: 250KBPS
    use_extended_id: true
    on_frame:
    - can_id:      0x0  # listen to all messages
      can_id_mask: 0x0
      use_extended_id: false
      then:
      - mqtt.publish:
          topic: !lambda |-
           return "vitocal/can/" + std::to_string(can_id);
          payload: !lambda |-
            // Include ArduinoJson
            DynamicJsonDocument doc(256);  // Adjust size as needed

            // Add CAN frame ID
            doc["can_id"] = can_id;
            for (size_t i = 0; i < x.size(); ++i) {
              doc["data"][i] = static_cast<int>(x[i]);
            }
            std::string json;
            serializeJson(doc, json);
            return json;
```
